feat: add cohosting.sh
ipfs-shipyard/cohosting pull request #3
Opened 2019-10-05 17:19 UTC by hacdias

So here's a first iteration of `cohosting.sh` with the following usage:

```
Usage:
	./cohosting.sh add <domain>...
	./cohosting.sh rm <domain>...
	./cohosting.sh ls [domain]...
	./cohosting.sh sync
	./cohosting.sh gc [n]
```

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

2019-10-05 17:20 UTC, hacdias commented
@lidel I think you're the best person to review this!

2019-10-06 10:48 UTC, hacdias commented
_Blocked by https://github.com/ipfs-shipyard/cohosting/issues/4_

2019-10-07 16:16 UTC, lidel requested changes
Thank you for creating this PoC, its really useful to have a simple script to experiment with the idea!

I think my comment at https://github.com/ipfs-shipyard/cohosting/issues/4#issuecomment-539090346 should unblock you.

2019-10-07 16:44 UTC, hacdias commented
@lidel it did! Just added that to the code and a few more printings to give progress info.

2019-10-08 19:28 UTC, lidel approved these changes
Thanks! Let's land this.

2019-10-08 19:28 UTC, merged